### ISSUE TITLE
Not able to execute ActivateProfile command

### ISSUE THREAD

**Issue by vikasgoyalgzs** [iloveicedgreentea/madvr-envy-homeassistant#11]
Hi,

Thank you for this amazing integation! I am able to use this to power on/off my madvr and see the attributes, but I have had no luck with any other command. Here is how I am sending it:

```
service: remote.send_command
data:
  command: ActivateProfile, SOURCE, 2
target:
  entity_id: remote.envy
```

I am not seeing any errors, but it just doesnt do anything.  I have also tried"
["ActivateProfile, SOURCE, 2"]
and
"ActivateProfile, SOURCE, 2"

I can confirm that the profile exists as I can see the correct profile info in attributes of this integration, when I manually switch profiles.

Please advise.  Thank you!

**Comment by iloveicedgreentea** [comment]
Thats the correct way to call it. Are you sure that profile exists and is activated? It works for me I just tried it out

ActivateProfile, SOURCE, 1 (or 2)

If it still doesnt work enable debug logs and try again. Its likely an issue with your profile if you dont get an error

**Comment by vikasgoyalgzs** [comment]
I dont know how to enable debugging on an entity that has been created directly via configuration.yaml. I usually click "enable debug logging" in the integration UI.
Can you please point me in the right direction?

Thank you!

**Comment by iloveicedgreentea** [comment]
add this to your config yaml and restart

```yaml
logger:
  default: warning
  logs:
    custom_components.madvr: debug
```
