### ISSUE TITLE
Unable to create trigger on `incoming_aspect_ratio`

### ISSUE THREAD

**Issue by binarylogic** [iloveicedgreentea/madvr-envy-homeassistant#8]
Hi, thanks for putting this integration together. I feel like I'm missing something, because I've wasted a lot of time trying to get a trigger to work.

Basically, what I'm trying to do is simple -- automate screen masking based on the MadVR `incoming_aspect_ratio`. Here's what I've done:

1. Successfully installed the integration via HACs (the "MadVR Envy" device is showing in my device list).
2. Added the integration in `configuration.yaml` and rebooted HA.
3. The "envy" remote successfully powers on and off the MadVR envy.

Yet, my trigger is not working, and there is nothing in the logs. Here's my trigger:

```yaml
- id: '1711827217350'
  alias: Unmask screen (MadVR)
  description: ''
  trigger:
  - platform: state
    entity_id:
    - remote.envy
    attribute: incoming_aspect_ratio
    to: '16:9'
  condition: []
  action:
  - device_id: 70201702a76dab4a4a54e596a48966f8
    domain: cover
    entity_id: 69cb4509b7200ba12d0cbf1ab6b7d106
    type: open
  - device_id: 70201702a76dab4a4a54e596a48966f8
    domain: cover
    entity_id: 10724a0c32d054dc07d8b680292bc99b
    type: open
  mode: single
 ```

**Comment by iloveicedgreentea** [comment]
Have you observed incoming_aspect_ratio changing? as far as I know envy will send whatever the container is which is usually 16:9, but detect the intended aspect ratio under something else in the AspectRatio message. You can try using `aspect_dec` which will be the detected aspect ratio as a float

```yaml
    if:
      - condition: numeric_state
        entity_id: remote.envy
        attribute: aspect_dec
        above: 0
        below: 1.8
```

**Comment by binarylogic** [comment]
Thanks for the response. Yes, I was finally able to observe state changes and get my automations working. Strangely, I had to use the remote manually once before I received these events. I'm not exactly sure why, but once I toggled the Envy on and off I started receiving state change events that I could build automations against.

For anyone stumbling across this, I added the following automations which mask and unmask my screen based on the MadVR aspect ratio.

Masking the screen:

```
- id: '1711828986473'
  alias: Mask Screen (MadVR)
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - remote.envy
    attribute: aspect_dec
    above: 1.8
  condition: []
  action:
  - device_id: 70201702a76dab4a4a54e596a48966f8
    domain: cover
    entity_id: 69cb4509b7200ba12d0cbf1ab6b7d106
    type: close
  - device_id: 70201702a76dab4a4a54e596a48966f8
    domain: cover
    entity_id: 10724a0c32d054dc07d8b680292bc99b
    type: close
  mode: single
```

Unmasking the screen:

```
- id: '1711827217350'
  alias: Unmask screen (MadVR)
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - remote.envy
    attribute: aspect_dec
    below: 1.8
  condition: []
  action:
  - device_id: 70201702a76dab4a4a54e596a48966f8
    domain: cover
    entity_id: 69cb4509b7200ba12d0cbf1ab6b7d106
    type: open
  - device_id: 70201702a76dab4a4a54e596a48966f8
    domain: cover
    entity_id: 10724a0c32d054dc07d8b680292bc99b
    type: open
  mode: single
```

`aspect_dec` is much easier, especially if you use non linear stretching for some of your aspect ratios.
